name: crypto_currencies
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  fl_chart: ^0.66.0
  flutter_widget_from_html: ^0.14.10+1
  google_fonts: ^6.1.0
  flutter_switch: ^0.3.2
  url_launcher: ^6.1.10
  flutter_linkify: ^6.0.0
  intl: ^0.19.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  html:

flutter:
  uses-material-design: true

  assets:
    - images/splash_screen.jpeg
    - screenshots/