name: crypto_currencies
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  fl_chart: ^0.70.2
  flutter_widget_from_html: ^0.16.0
  google_fonts: ^6.2.1
  flutter_switch: ^0.3.2
  url_launcher: ^6.3.1
  flutter_linkify: ^6.0.0
  intl: ^0.19.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/splash_screen.jpeg
    - screenshots/