name: crypto_currencies
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  fl_chart: ^0.55.2
  flutter_widget_from_html: ^0.9.1
  google_fonts: ^4.0.3
  flutter_switch: ^0.3.2
  url_launcher: ^6.1.10
  flutter_linkify: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  html:

flutter:
  uses-material-design: true

  assets:
    - images/splash_screen.jpeg